name: "[DEV] Frontend Deployment"

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SSH_KEY_NAME: "~/.ssh/ssh_key"

  IMAGE_NAME: "mxf-frontend-dev"
  CONTAINER_NAME: "mxf-frontend-dev"
  IMAGE_TAR: "/tmp/mxf-frontend-dev.tar.gz"
  REMOTE_TMP_DIR: "/tmp/mxf-frontend-dev"
  DOCKER_NETWORK_NAME: "mxf-network-dev"


jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.TAG }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create tag from GitHub SHA and set it as an output
        id: set_tag
        run: echo "TAG=`echo ${{ github.sha }} | cut -c1-7`" >> $GITHUB_OUTPUT

      - name: Create .env file
        run: |
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" > .env

      - name: Prepare SSH connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.SERVER_SSH_KEY }}" > ${{ env.SSH_KEY_NAME }}
          chmod 600 ${{ env.SSH_KEY_NAME }}
          touch ~/.ssh/known_hosts || true
          ssh-keyscan -H ${{ env.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Set up Docker Build action
        uses: docker/setup-buildx-action@v3

      - name: Build and export Docker Image
        uses: docker/build-push-action@v6
        env:
          TAG: ${{ steps.set_tag.outputs.TAG }}
        with:
          context: .
          tags: ${{ env.IMAGE_NAME }}:latest, ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          outputs: type=docker,dest=${{ env.IMAGE_TAR }}

      - name: Upload Docker Image artifact to GitHub
        uses: actions/upload-artifact@v4
        env:
          TAG: ${{ steps.set_tag.outputs.TAG }}
        with:
          name: ${{ env.IMAGE_NAME }}-${{ env.TAG }}
          path: ${{ env.IMAGE_TAR }}
          if-no-files-found: error
          retention-days: 1

      - name: Create remote directory and copy files
        run: |
          ssh -i ${{ env.SSH_KEY_NAME }} ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} "mkdir -p ${{ env.REMOTE_TMP_DIR }}"
          scp -i ${{ env.SSH_KEY_NAME }} .env ${{ env.SERVER_USER }}@${{ env.SERVER_IP }}:${{ env.REMOTE_TMP_DIR }}/.env
          scp -i ${{ env.SSH_KEY_NAME }} ${{ env.IMAGE_TAR }} ${{ env.SERVER_USER }}@${{ env.SERVER_IP }}:${{ env.REMOTE_TMP_DIR }}/mxf-frontend-dev.tar.gz

  deploy:
    needs: build-and-upload
    runs-on: ubuntu-latest
    steps:
      - name: Prepare SSH connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.SERVER_SSH_KEY }}" > ${{ env.SSH_KEY_NAME }}
          chmod 600 ${{ env.SSH_KEY_NAME }}
          touch ~/.ssh/known_hosts || true
          ssh-keyscan -H ${{ env.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -i ${{ env.SSH_KEY_NAME }} ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} << 'EOF'
            docker load < ${{ env.REMOTE_TMP_DIR }}/mxf-frontend-dev.tar.gz
            docker network create ${{ env.DOCKER_NETWORK_NAME }} || true
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true
            docker run -d \
            --restart unless-stopped \
            --env-file ${{ env.REMOTE_TMP_DIR }}/.env \
            --name ${{ env.CONTAINER_NAME }} \
            -p 8080:8080 \
            --network ${{ env.DOCKER_NETWORK_NAME }} \
            ${{ env.IMAGE_NAME }}:latest \
            npm run start:dev
          EOF